# Generated by Django 4.0.4 on 2022-04-23 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id_aluno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.IntegerField()),
                ('disciplina', models.CharField(max_length=255)),
                ('nota01', models.BooleanField()),
                ('nota02', models.BooleanField()),
                ('nota03', models.BooleanField()),
                ('nota04', models.BooleanField()),
                ('media', models.BooleanField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
