# Generated by Django 4.0.4 on 2022-04-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='media',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota01',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota02',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota03',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota04',
            field=models.FloatField(),
        ),
    ]
