# Generated by Django 4.0.1 on 2022-05-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_notas_media_alter_notas_nota01_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='media',
        ),
    ]
